apiVersion: apps/v1
kind: Deployment
metadata:
  name: paigow-game
  labels:
    app: paigow-game
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paigow-game
  template:
    metadata:
      labels:
        app: paigow-game
    spec:
      containers:
      - name: paigow-game
        image: gcr.io/YOUR_PROJECT_ID/paigow-game:latest
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: paigow-game-service
spec:
  selector:
    app: paigow-game
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer